import { useState, useEffect, useRef, useCallback } from 'react'
import axios from 'axios'
import Flashcards from './Flashcards'
import QuizMode from './QuizMode'
import VoicePractice from './VoicePractice'
import TopicChat from './TopicChat'
import XPBar from './XPBar'
import StreakCounter from './StreakCounter'
import SessionSummary from './SessionSummary'
import { useGamification } from '../contexts/GamificationContext'
import { api } from '../utils/api'
import './Practice.css'

function Practice({ questions, jobDescription, companyName, roleTitle, techStack, jobDescriptionHash, studyTopics, initialFocusCategories, initialSmartMode, initialMode }) {
  const [practiceMode, setPracticeMode] = useState(initialMode || 'flashcards')
  const [voiceMode, setVoiceMode] = useState(initialMode === 'voice')
  const [allQuestions, setAllQuestions] = useState(questions || [])
  const [generating, setGenerating] = useState(false)
  const [generateError, setGenerateError] = useState(null)
  const [sessionId, setSessionId] = useState(null)
  const [sessionStats, setSessionStats] = useState({ questionsAnswered: 0, totalXp: 0 })
  const [showSummary, setShowSummary] = useState(false)
  const [summaryData, setSummaryData] = useState(null)
  const [focusCategories, setFocusCategories] = useState(initialFocusCategories || [])
  const [lastXpGain, setLastXpGain] = useState(0)
  const [autoGenerateAttempted, setAutoGenerateAttempted] = useState(false)
  const [questionsExhausted, setQuestionsExhausted] = useState(false)
  const sessionIdRef = useRef(null)
  const { refreshStats, addXp } = useGamification() || {}

  // Map initialMode to the correct internal mode
  useEffect(() => {
    if (initialMode === 'voice') {
      setPracticeMode('quiz')
      setVoiceMode(true)
    } else if (initialMode) {
      setPracticeMode(initialMode)
      setVoiceMode(false)
    }
  }, [initialMode])

  // Start session on mount
  useEffect(() => {
    if (!jobDescriptionHash) return
    const startSession = async () => {
      try {
        const res = await api.practice.startSession({
          jobDescriptionHash,
          mode: practiceMode,
        })
        setSessionId(res.data.sessionId)
        sessionIdRef.current = res.data.sessionId
      } catch (err) {
        console.error('Failed to start practice session:', err)
      }
    }
    startSession()

    return () => {
      if (sessionIdRef.current) {
        api.practice.endSession({ sessionId: sessionIdRef.current }).catch(() => {})
      }
    }
  }, [jobDescriptionHash])

  // Auto-generate more questions if fewer than 10
  useEffect(() => {
    if (autoGenerateAttempted || !jobDescriptionHash || allQuestions.length >= 10 || generating) return
    const storageKey = `autoGenerated_${jobDescriptionHash}`
    if (sessionStorage.getItem(storageKey)) return
    setAutoGenerateAttempted(true)
    sessionStorage.setItem(storageKey, '1')
    handleGenerateMore(true)
  }, [jobDescriptionHash, allQuestions.length])

  // Smart practice ordering (always on)
  useEffect(() => {
    if (!jobDescriptionHash || !allQuestions.length) return
    const reorder = async () => {
      try {
        const res = await api.practice.getSmartOrder({
          jobDescriptionHash,
          questions: allQuestions,
        })
        if (res.data.questions) {
          setAllQuestions(res.data.questions)
        }
      } catch (err) {
        console.error('Smart ordering failed:', err)
      }
    }
    reorder()
  }, [jobDescriptionHash])

  // Filter questions by focus categories (silently via URL params)
  const displayQuestions = focusCategories.length > 0
    ? allQuestions.filter(q => {
        const cat = (q.category || '').toLowerCase()
        return focusCategories.some(fc => fc.toLowerCase() === cat)
      })
    : allQuestions

  const handleXpGained = useCallback((xpData) => {
    if (!xpData) return
    setLastXpGain(xpData.xpEarned || 0)
    setSessionStats(prev => ({
      questionsAnswered: prev.questionsAnswered + 1,
      totalXp: prev.totalXp + (xpData.xpEarned || 0),
    }))
    if (addXp) {
      addXp(xpData.xpEarned || 0, xpData.newAchievements, xpData.levelUp, xpData.levelTitle)
    }
  }, [addXp])

  const handleEndSession = async () => {
    if (!sessionId) {
      setShowSummary(false)
      return
    }
    try {
      const res = await api.practice.endSession({ sessionId })
      setSummaryData({
        questionsAttempted: res.data.session?.questions_attempted || sessionStats.questionsAnswered,
        questionsCorrect: res.data.session?.questions_correct || 0,
        averageScore: res.data.session?.average_score || 0,
        totalXpEarned: res.data.xpEarned || sessionStats.totalXp,
        achievements: res.data.achievements || [],
        streakUpdate: res.data.streakUpdate,
      })
      setShowSummary(true)
      sessionIdRef.current = null
      if (refreshStats) refreshStats()
    } catch (err) {
      console.error('Failed to end session:', err)
      setShowSummary(false)
    }
  }

  const handleContinuePractice = async () => {
    setShowSummary(false)
    setSummaryData(null)
    setSessionStats({ questionsAnswered: 0, totalXp: 0 })
    try {
      const res = await api.practice.startSession({
        jobDescriptionHash,
        mode: practiceMode,
      })
      setSessionId(res.data.sessionId)
      sessionIdRef.current = res.data.sessionId
    } catch (err) {
      console.error('Failed to restart session:', err)
    }
  }

  const handleGenerateMore = async (silent = false) => {
    if (!jobDescriptionHash) {
      if (!silent) setGenerateError('Job description hash is required')
      return
    }
    setGenerating(true)
    if (!silent) setGenerateError(null)
    try {
      const response = await axios.post('/api/questions/generate-more', {
        jobDescriptionHash,
        existingQuestions: allQuestions,
        companyName,
        roleTitle,
        techStack
      })
      if (response.data.success && response.data.questions) {
        setAllQuestions(prev => [...prev, ...response.data.questions])
        setQuestionsExhausted(false)
      } else if (!silent) {
        setGenerateError('Failed to generate questions')
      }
    } catch (error) {
      if (!silent) {
        setGenerateError(error.response?.data?.error || 'Failed to generate questions')
      }
    } finally {
      setGenerating(false)
    }
  }

  // Called by child components when user reaches the end of questions
  const handleQuestionsExhausted = useCallback(() => {
    setQuestionsExhausted(true)
  }, [])

  if (!allQuestions || allQuestions.length === 0) {
    if (generating) {
      return (
        <div className="practice-empty">
          <div className="practice-generating">
            <div className="generating-spinner" />
            <p>Generating practice questions...</p>
          </div>
        </div>
      )
    }
    return <div className="practice-empty">No questions available for practice</div>
  }

  return (
    <div className="practice-container">
      {showSummary && summaryData && (
        <SessionSummary
          session={summaryData}
          onContinue={handleContinuePractice}
          onEnd={() => setShowSummary(false)}
        />
      )}

      <div className="practice-header">
        <div>
          <p className="practice-question-count">
            {displayQuestions.length} questions
            {(() => {
              const cats = new Set(displayQuestions.map(q => q.category).filter(Boolean))
              return cats.size > 1 ? ` across ${cats.size} topics` : ''
            })()}
            {generating && <span className="practice-loading-hint"> &middot; Loading more...</span>}
            {sessionStats.questionsAnswered > 0 && (
              <span> &middot; {sessionStats.questionsAnswered} answered</span>
            )}
            {sessionStats.totalXp > 0 && (
              <span className="session-xp-count"> &middot; +{sessionStats.totalXp} XP</span>
            )}
          </p>
        </div>
        <div className="practice-header-right">
          <StreakCounter compact />
          <XPBar xpGained={lastXpGain} compact />
          <button
            className="mode-btn"
            onClick={handleEndSession}
            style={{ fontSize: '12px', padding: '8px 14px', borderColor: '#f59e0b33', color: '#f59e0b' }}
          >
            End Session
          </button>
        </div>
      </div>

      {generateError && (
        <div className="practice-error" style={{ marginBottom: '16px', padding: '12px', background: '#3a1a1a', border: '1px solid #5a2a2a', borderRadius: '6px', color: '#ff6b6b' }}>
          {generateError}
        </div>
      )}

      {/* Generate More — only when questions exhausted */}
      {questionsExhausted && (
        <div className="practice-generate-more-bar">
          <span className="practice-exhausted-text">You've gone through all questions!</span>
          <button
            className="generate-more-btn"
            onClick={() => handleGenerateMore(false)}
            disabled={generating || !jobDescriptionHash}
            title="Generate 10-15 more unique questions (5 credits)"
          >
            {generating ? 'Generating...' : 'Generate More Questions'}
          </button>
        </div>
      )}

      <div className="practice-content">
        {practiceMode === 'flashcards' && (
          <Flashcards
            questions={displayQuestions}
            jobDescriptionHash={jobDescriptionHash}
            sessionId={sessionId}
            onXpGained={handleXpGained}
            onGenerateMore={() => handleGenerateMore(false)}
            generating={generating}
            onQuestionsExhausted={handleQuestionsExhausted}
          />
        )}
        {practiceMode === 'quiz' && (
          <div className="quiz-with-voice">
            {voiceMode ? (
              <VoicePractice
                questions={displayQuestions}
                jobDescription={jobDescription}
                jobDescriptionHash={jobDescriptionHash}
                sessionId={sessionId}
                onXpGained={handleXpGained}
              />
            ) : (
              <QuizMode
                questions={displayQuestions}
                jobDescription={jobDescription}
                jobDescriptionHash={jobDescriptionHash}
                sessionId={sessionId}
                onXpGained={handleXpGained}
              />
            )}
          </div>
        )}
        {practiceMode === 'chat' && (
          <TopicChat
            jobDescription={jobDescription}
            companyName={companyName}
            roleTitle={roleTitle}
            techStack={techStack}
            jobDescriptionHash={jobDescriptionHash}
            sessionId={sessionId}
            onXpGained={handleXpGained}
            studyTopics={studyTopics}
          />
        )}
      </div>
    </div>
  )
}

export default Practice
