import { useState, useEffect, useRef, useCallback } from 'react'
import axios from 'axios'
import Flashcards from './Flashcards'
import QuizMode from './QuizMode'
import VoicePractice from './VoicePractice'
import TopicChat from './TopicChat'
import { api } from '../utils/api'
import './Practice.css'

function Practice({ questions, jobDescription, companyName, roleTitle, techStack, jobDescriptionHash, studyTopics, initialFocusCategories, initialSmartMode, initialMode }) {
  const [practiceMode, setPracticeMode] = useState(initialMode || 'flashcards')
  const [voiceMode, setVoiceMode] = useState(initialMode === 'voice')
  const [allQuestions, setAllQuestions] = useState(questions || [])
  const [generating, setGenerating] = useState(false)
  const [generateError, setGenerateError] = useState(null)
  const [sessionId, setSessionId] = useState(null)
  const [sessionStats, setSessionStats] = useState({ questionsAnswered: 0 })
  const [showSummary, setShowSummary] = useState(false)
  const [summaryData, setSummaryData] = useState(null)
  const [focusCategories, setFocusCategories] = useState(initialFocusCategories || [])
  const [autoGenerateAttempted, setAutoGenerateAttempted] = useState(false)
  const [questionsExhausted, setQuestionsExhausted] = useState(false)
  const [questionTarget, setQuestionTarget] = useState(10)
  const [autoStopTriggered, setAutoStopTriggered] = useState(false)
  const sessionIdRef = useRef(null)

  // Map initialMode to the correct internal mode
  useEffect(() => {
    if (initialMode === 'voice') {
      setPracticeMode('quiz')
      setVoiceMode(true)
    } else if (initialMode) {
      setPracticeMode(initialMode)
      setVoiceMode(false)
    }
  }, [initialMode])

  // Start session on mount
  useEffect(() => {
    if (!jobDescriptionHash) return
    const startSession = async () => {
      try {
        const res = await api.practice.startSession({
          jobDescriptionHash,
          mode: practiceMode,
        })
        setSessionId(res.data.sessionId)
        sessionIdRef.current = res.data.sessionId
      } catch (err) {
        console.error('Failed to start practice session:', err)
      }
    }
    startSession()

    return () => {
      if (sessionIdRef.current) {
        api.practice.endSession({ sessionId: sessionIdRef.current }).catch(() => {})
      }
    }
  }, [jobDescriptionHash])

  // Auto-generate more questions if fewer than 10
  useEffect(() => {
    if (autoGenerateAttempted || !jobDescriptionHash || allQuestions.length >= 10 || generating) return
    const storageKey = `autoGenerated_${jobDescriptionHash}`
    if (sessionStorage.getItem(storageKey)) return
    setAutoGenerateAttempted(true)
    sessionStorage.setItem(storageKey, '1')
    handleGenerateMore(true)
  }, [jobDescriptionHash, allQuestions.length])

  // Smart practice ordering (always on)
  useEffect(() => {
    if (!jobDescriptionHash || !allQuestions.length) return
    const reorder = async () => {
      try {
        const res = await api.practice.getSmartOrder({
          jobDescriptionHash,
          questions: allQuestions,
        })
        if (res.data.questions) {
          setAllQuestions(res.data.questions)
        }
      } catch (err) {
        console.error('Smart ordering failed:', err)
      }
    }
    reorder()
  }, [jobDescriptionHash])

  // Filter questions by focus categories (silently via URL params)
  const displayQuestions = focusCategories.length > 0
    ? allQuestions.filter(q => {
        const cat = (q.category || '').toLowerCase()
        return focusCategories.some(fc => fc.toLowerCase() === cat)
      })
    : allQuestions

  const handleAnswerRecorded = useCallback(() => {
    setSessionStats(prev => ({
      questionsAnswered: prev.questionsAnswered + 1,
    }))
  }, [])

  // Auto-stop when question target reached
  useEffect(() => {
    if (
      questionTarget > 0 &&
      sessionStats.questionsAnswered > 0 &&
      sessionStats.questionsAnswered >= questionTarget &&
      !autoStopTriggered &&
      !showSummary
    ) {
      setAutoStopTriggered(true)
      handleEndSession()
    }
  }, [sessionStats.questionsAnswered, questionTarget, autoStopTriggered, showSummary])

  const handleContinueMore = async () => {
    setAutoStopTriggered(false)
    setQuestionTarget(prev => prev + 5)
    setShowSummary(false)
    setSummaryData(null)
    // Don't reset stats — keep cumulative count but start new server session
    try {
      const res = await api.practice.startSession({
        jobDescriptionHash,
        mode: practiceMode,
      })
      setSessionId(res.data.sessionId)
      sessionIdRef.current = res.data.sessionId
    } catch (err) {
      console.error('Failed to restart session:', err)
    }
  }

  const handleEndSession = async () => {
    if (!sessionId) {
      setShowSummary(false)
      return
    }
    try {
      const res = await api.practice.endSession({ sessionId })
      setSummaryData({
        questionsAttempted: res.data.session?.questions_attempted || sessionStats.questionsAnswered,
        questionsCorrect: res.data.session?.questions_correct || 0,
        averageScore: res.data.session?.average_score || 0,
      })
      setShowSummary(true)
      sessionIdRef.current = null
    } catch (err) {
      console.error('Failed to end session:', err)
      setShowSummary(false)
    }
  }

  const handleContinuePractice = async () => {
    setShowSummary(false)
    setSummaryData(null)
    setSessionStats({ questionsAnswered: 0 })
    try {
      const res = await api.practice.startSession({
        jobDescriptionHash,
        mode: practiceMode,
      })
      setSessionId(res.data.sessionId)
      sessionIdRef.current = res.data.sessionId
    } catch (err) {
      console.error('Failed to restart session:', err)
    }
  }

  const handleGenerateMore = async (silent = false) => {
    if (!jobDescriptionHash) {
      if (!silent) setGenerateError('Job description hash is required')
      return
    }
    setGenerating(true)
    if (!silent) setGenerateError(null)
    try {
      const response = await axios.post('/api/questions/generate-more', {
        jobDescriptionHash,
        existingQuestions: allQuestions,
        companyName,
        roleTitle,
        techStack
      })
      if (response.data.success && response.data.questions) {
        setAllQuestions(prev => [...prev, ...response.data.questions])
        setQuestionsExhausted(false)
      } else if (!silent) {
        setGenerateError('Failed to generate questions')
      }
    } catch (error) {
      if (!silent) {
        setGenerateError(error.response?.data?.error || 'Failed to generate questions')
      }
    } finally {
      setGenerating(false)
    }
  }

  // Called by child components when user reaches the end of questions
  const handleQuestionsExhausted = useCallback(() => {
    setQuestionsExhausted(true)
  }, [])

  if (!allQuestions || allQuestions.length === 0) {
    if (generating) {
      return (
        <div className="practice-empty">
          <div className="practice-generating">
            <div className="generating-spinner" />
            <p>Generating practice questions...</p>
          </div>
        </div>
      )
    }
    return <div className="practice-empty">No questions available for practice</div>
  }

  return (
    <div className="practice-container">
      {showSummary && summaryData && (
        <div className="practice-summary-overlay">
          <div className="practice-summary-card">
            <h3>{autoStopTriggered ? `${questionTarget} Questions Done!` : 'Session Complete'}</h3>
            <div className="practice-summary-stats">
              <div className="practice-summary-stat">
                <span className="practice-summary-stat-value">{summaryData.questionsAttempted}</span>
                <span className="practice-summary-stat-label">Questions</span>
              </div>
              <div className="practice-summary-stat">
                <span className="practice-summary-stat-value">{summaryData.questionsCorrect}</span>
                <span className="practice-summary-stat-label">Correct</span>
              </div>
              {summaryData.averageScore > 0 && (
                <div className="practice-summary-stat">
                  <span className="practice-summary-stat-value">{Math.round(summaryData.averageScore)}%</span>
                  <span className="practice-summary-stat-label">Avg Score</span>
                </div>
              )}
            </div>
            <div className="practice-summary-actions">
              {autoStopTriggered && (
                <button className="practice-continue-btn" onClick={handleContinueMore}>
                  Continue +5 more
                </button>
              )}
              <button className="practice-restart-btn" onClick={handleContinuePractice}>New Session</button>
              <button className="practice-close-btn" onClick={() => setShowSummary(false)}>Close</button>
            </div>
          </div>
        </div>
      )}

      <div className="practice-header">
        <div>
          <p className="practice-question-count">
            {displayQuestions.length} questions
            {(() => {
              const cats = new Set(displayQuestions.map(q => q.category).filter(Boolean))
              return cats.size > 1 ? ` across ${cats.size} topics` : ''
            })()}
            {generating && <span className="practice-loading-hint"> &middot; Loading more...</span>}
            {sessionStats.questionsAnswered > 0 && (
              <span> &middot; {sessionStats.questionsAnswered}/{questionTarget} answered</span>
            )}
          </p>
        </div>
        <div className="practice-header-right">
          <div className="practice-target-selector">
            <label className="practice-target-label">Goal:</label>
            <select
              className="practice-target-select"
              value={questionTarget}
              onChange={(e) => {
                setQuestionTarget(Number(e.target.value))
                setAutoStopTriggered(false)
              }}
            >
              <option value={5}>5 questions</option>
              <option value={10}>10 questions</option>
              <option value={15}>15 questions</option>
              <option value={20}>20 questions</option>
            </select>
          </div>
          <button
            className="practice-end-btn"
            onClick={handleEndSession}
          >
            End Session
          </button>
        </div>
      </div>

      {generateError && (
        <div className="practice-error" style={{ marginBottom: '16px', padding: '12px', background: '#3a1a1a', border: '1px solid #5a2a2a', borderRadius: '6px', color: '#ff6b6b' }}>
          {generateError}
        </div>
      )}

      {/* Generate More — only when questions exhausted */}
      {questionsExhausted && (
        <div className="practice-generate-more-bar">
          <span className="practice-exhausted-text">You've gone through all questions!</span>
          <button
            className="generate-more-btn"
            onClick={() => handleGenerateMore(false)}
            disabled={generating || !jobDescriptionHash}
            title="Generate 10-15 more unique questions (5 credits)"
          >
            {generating ? 'Generating...' : 'Generate More Questions'}
          </button>
        </div>
      )}

      <div className="practice-content">
        {practiceMode === 'flashcards' && (
          <Flashcards
            questions={displayQuestions}
            jobDescriptionHash={jobDescriptionHash}
            sessionId={sessionId}
            onXpGained={handleAnswerRecorded}
            onGenerateMore={() => handleGenerateMore(false)}
            generating={generating}
            onQuestionsExhausted={handleQuestionsExhausted}
          />
        )}
        {practiceMode === 'quiz' && (
          <div className="quiz-with-voice">
            {voiceMode ? (
              <VoicePractice
                questions={displayQuestions}
                jobDescription={jobDescription}
                jobDescriptionHash={jobDescriptionHash}
                sessionId={sessionId}
                onXpGained={handleAnswerRecorded}
              />
            ) : (
              <QuizMode
                questions={displayQuestions}
                jobDescription={jobDescription}
                jobDescriptionHash={jobDescriptionHash}
                sessionId={sessionId}
                onXpGained={handleAnswerRecorded}
              />
            )}
          </div>
        )}
        {practiceMode === 'chat' && (
          <TopicChat
            jobDescription={jobDescription}
            companyName={companyName}
            roleTitle={roleTitle}
            techStack={techStack}
            jobDescriptionHash={jobDescriptionHash}
            sessionId={sessionId}
            onXpGained={handleAnswerRecorded}
            studyTopics={studyTopics}
          />
        )}
      </div>
    </div>
  )
}

export default Practice
